# Generated by Django 4.2.4 on 2024-04-12 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registeredemails",
            name="subscribed_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registeredemails",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
